# Generated by Django 3.0.7 on 2019-02-14 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40, unique=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('added_date',),
            },
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('parent', 'Parent'), ('teaching_staff', 'Teachingstaff'), ('nonteachingstaff', 'NonTeachingstaff')], default='student', max_length=30)),
                ('role_name_added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('role_name',),
            },
        ),
        migrations.CreateModel(
            name='UtamuAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, unique=True)),
                ('lastname', models.CharField(max_length=20)),
                ('Uemail', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('residence', models.CharField(max_length=30)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('reg_date',),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studentprofiling_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('StudentCourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_course_name', to='API.Courses')),
                ('StudentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member_name', to='API.UtamuAccount')),
                ('StudentRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_role_name', to='API.MemberRole')),
            ],
            options={
                'ordering': ('Studentprofiling_date',),
            },
        ),
        migrations.CreateModel(
            name='StaffMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffMemberprofiling_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('StaffMemberCourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members_course_name', to='API.Courses')),
                ('StaffMemberId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_Member_name', to='API.UtamuAccount')),
                ('StaffMemberRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members_role_name', to='API.MemberRole')),
            ],
            options={
                'ordering': ('StaffMemberprofiling_date',),
            },
        ),
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_body', models.TextField(max_length=100000)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posters_name', to='API.StudentProfile')),
            ],
            options={
                'ordering': ('posting_date',),
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetitle', models.CharField(max_length=30)),
                ('messagebody', models.TextField(max_length=100000)),
                ('sendingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('recievername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_name', to='API.StudentProfile')),
                ('sendername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_name', to='API.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_marks', models.CharField(max_length=10)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_marked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_course', to='API.Courses')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorder', to='API.StaffMemberProfile')),
                ('student_marked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='API.StudentProfile')),
            ],
        ),
    ]
