# Generated by Django 3.0.7 on 2019-02-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='StudentMaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utamuaccount',
            name='lastname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
