# Generated by Django 3.0.7 on 2020-07-03 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190214_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=100000)),
                ('image', models.FileField(null=True, upload_to='')),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='StudentMaker',
        ),
    ]
