# Generated by Django 3.0.7 on 2020-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200703_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouseldisplay',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%d/%a/%b/%H/%M/%S'),
        ),
    ]
