# Generated by Django 3.0.7 on 2020-08-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200814_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('pic', models.ImageField(blank=True, upload_to='pics')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carouseldisplay',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%b/%a/%d/%H/%M'),
        ),
    ]
