# Generated by Django 3.0.7 on 2019-02-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200817_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
