# Generated by Django 3.0.7 on 2020-09-27 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_marks', models.CharField(max_length=10)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorder', to='API.StaffMemberProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Respondentprofiling_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('Respondentprofiling_date',),
            },
        ),
        migrations.CreateModel(
            name='SurveyTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=40, unique=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('added_date',),
            },
        ),
        migrations.CreateModel(
            name='YaridAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, unique=True)),
                ('lastname', models.CharField(max_length=20, unique=True)),
                ('Uemail', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('residence', models.CharField(max_length=30)),
                ('country_of_origin', models.CharField(max_length=30)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('reg_date',),
            },
        ),
        migrations.CreateModel(
            name='YaridMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('respondent', 'respondent'), ('staff', 'Staff'), ('adminstaff', 'AdminStaff'), ('parent', 'Parent')], default='student', max_length=30)),
                ('role_name_added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('role_name',),
            },
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='StudentCourse',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='StudentId',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='StudentRole',
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='poster_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posters_name', to='API.StaffMemberProfile'),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='RespondentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member_name', to='API.YaridAccount'),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='RespondentRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_role_name', to='API.YaridMemberRole'),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='RespondentSurveyTopics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_course_name', to='API.SurveyTopics'),
        ),
        migrations.AddField(
            model_name='kudos',
            name='respondent_marked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='API.RespondentProfile'),
        ),
        migrations.AddField(
            model_name='kudos',
            name='survey_marked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_course', to='API.SurveyTopics'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='recievername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_name', to='API.RespondentProfile'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sendername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_name', to='API.RespondentProfile'),
        ),
        migrations.AlterField(
            model_name='staffmemberprofile',
            name='StaffMemberCourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members_course_name', to='API.SurveyTopics'),
        ),
        migrations.AlterField(
            model_name='staffmemberprofile',
            name='StaffMemberId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_Member_name', to='API.YaridAccount'),
        ),
        migrations.AlterField(
            model_name='staffmemberprofile',
            name='StaffMemberRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members_role_name', to='API.YaridMemberRole'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='MemberRole',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='UtamuAccount',
        ),
    ]
