# Generated by Django 3.0.7 on 2020-09-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200927_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='poster_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posters_name', to='API.RespondentProfile'),
        ),
    ]
