# Generated by Django 3.0.7 on 2020-09-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200927_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondentprofile',
            name='RespondentSurveyTopics',
        ),
    ]
