# Generated by Django 3.0.7 on 2020-09-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_remove_respondentprofile_respondentsurveytopics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondentprofile',
            old_name='RespondentId',
            new_name='RespondentName',
        ),
    ]
