# Generated by Django 3.0.7 on 2020-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20200927_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='post_image',
            field=models.ImageField(null=True, upload_to='images/%Y/%b/%a/%d/%H/%M'),
        ),
    ]
