# Generated by Django 3.0.7 on 2020-09-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_newsposts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yaridmemberrole',
            name='role_name',
            field=models.CharField(choices=[('respondent', 'respondent'), ('staff', 'Staff'), ('adminstaff', 'AdminStaff'), ('parent', 'Parent')], default='student', max_length=30, unique=True),
        ),
    ]
