# Generated by Django 3.0.7 on 2020-09-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20200927_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yaridaccount',
            old_name='firstname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='yaridaccount',
            name='accounTimage',
            field=models.ImageField(null=True, upload_to='images/%Y/%b/%a/%d/%H/%M'),
        ),
    ]
