# Generated by Django 3.0.7 on 2020-09-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20200927_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yaridaccount',
            name='accounTimage',
        ),
    ]
